- repository: autowarefoundation/autoware.universe
  files:
    # tier4_autoware_api_launch

    # tier4_control_launch

    # tier4_localization_launch

    # tier4_map_launch
    - source: launch/tier4_map_launch/config/pointcloud_map_loader.param.yaml
      dest: autoware_launch/config/tier4_map_launch/pointcloud_map_loader.param.yaml

    # tier4_perception_launch

    # tier4_planning_launch

    # tier4_sensing_launch

    # tier4_simulator_launch

    # tier4_system_launch

    # tier4_vehicle_launch
